server:
  port: 5555

spring:
  profiles:
    active: prod
  application:
    name: my-gateway
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
      enabled: true
zuul:
  sensitive-headers:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


application:
  regex:
    static-resources: \.(js|map|woff2|png|gif|bmp|icon|ico|css|html)($|\?)
  ignored-url: